# Generated by Django 3.1.5 on 2021-01-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitman',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
