# Generated by Django 3.1.5 on 2021-01-13 02:08

from django.db import migrations
from django.core.management import call_command


def load_hitmen(*args):
    call_command("loaddata", "hits")


def delete_hitmen(apps, *args):
    Hitman = apps.get_model("hits", "Hitman")
    Hitman.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0003_auto_20210112_2143'),
    ]

    operations = [migrations.RunPython(load_hitmen, delete_hitmen)]
